language: cpp
compiler: gcc
before_script:
    - sudo apt-get -qq update
    - sudo apt-get install libboost-all-dev
script: "make chivvy TEST=true"

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
